---
- name: Launch messages producer container
  docker_container:
    name: rawdataconsumer
    image: cquezadav/rawdataconsumer
    state: started
    log_driver: json-file
    log_options:
      max-size: "200m"
      max-file: "1"
    env:
      CASSANDRA_HOST: "{{ cassandra_host  }}"
      KAFKA_HOST: "{{ kafka_host }}"
      MESSAGES_TIME_WINDOW: 2000
