version: '3'
services:
  zeppelin:
    container_name: zeppelin
    image: cquezadav/zeppelin
    ports:
      - "8081:8080"
    volumes:
      - $PWD/notebooks:/usr/zeppelin/notebook
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"

  zookeeper:
    container_name: zookeeper
    image: cquezadav/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
  kafka:
    container_name: kafka
    image: cquezadav/kafka
    ports:
      - "9092:9092"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    extra_hosts:
     - "dockerhost:${_DOCKER_HOST}"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: dockerhost
      KAFKA_CREATE_TOPICS: "storestreams:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    container_name: cassandra
    image: cassandra:3.10
    ports:
      - "9042:9042"
      - "9160:9160"
    #volumes:
      #- $PWD/cassandra:/var/lib/cassandra
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "1"