version: '2'
services:
  zeppelin:
    container_name: zeppelin
    image: cquezadav/zeppelin
    ports:
      - "8081:8080"
    volumes:
      - $PWD/notebooks:/usr/zeppelin/notebook
  zookeeper:
    container_name: zookeeper
    image: cquezadav/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: cquezadav/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "storestreams:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
