---

- name: Create an ec2 instance
  ec2:
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
     key_name: "{{ keypair }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type}}"
     image: "{{ ami }}"
     wait: true
     region: "{{ region }}"
     count: 1  # default
    #  count_tag:
    #     Name: Kafka
     instance_tags:
        Name: "{{ instance_name }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: "{{ assign_public_ip }}"
     volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
  register: ec2_facts

- name: add public dns to host
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: "{{ target_pub }}"
  with_items: "{{ ec2_facts.instances }}"

# - name: add private ip to host
#   add_host:
#     name: "{{ item.private_ip }}"
#     groups: "{{ target_priv }}"
#   with_items: "{{ ec2_facts.instances }}"

- name: add public ip to host
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ target_pub_ip }}"
  with_items: "{{ ec2_facts.instances }}"

# - name: Make vars persistant
#   set_fact:
#     new_host: "{{ item.public_dns_name }}"
#   with_items: "{{ ec2_facts.instances }}"
#
# - debug:
#     msg= "{{ new_host }}"

# - debug:
#     msg="{{ hostvars[groups['"{{ target_pub }}"'][0]] }}"
#
# - debug:
#     msg="{{ hostvars[groups['"{{ target_priv }}"'][0]] }}"

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{ item.public_ip }} port=22 delay=30 timeout=320 state=started
  with_items: "{{ ec2_facts.instances }}"

# - pause:
#     minutes: 1
