---
- name: Create ec2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
      - "../config/default.yml"

  vars:
    # EC2 configuration
    instance_type: t2.nano
    instance_name: new-instance
    security_group: default-ssh
    # host group name
    target_pub: target_pub
    target_pub_ip: target_pub_ip

  roles:
    - ec2

- name: Add pub key
  hosts: target_pub
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
      - "../config/default.yml"

  roles:
    - provision_python
    - add_authorized_key
