---
- name: Create ec2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
      - "../config/default.yml"
  vars:
    # EC2 configuration
    instance_type: t2.micro
    instance_name: Messages producer
    security_group: ['storestreams', 'default-ssh']
    target_pub: target_messagesproducer_pub
    target_pub_ip: target_messagesproducer_pub_ip

  roles:
    - ec2

- name: Provision python to be able to get the facts
  hosts: target_messagesproducer_pub
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
      - "../config/default.yml"

  roles:
    - provision_python

- name: Install messagesproducer
  hosts: target_messagesproducer_pub
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
      - "../config/default.yml"
  vars:
    kafka_host: "{{ hostvars[groups['target_kafka_pub_ip'][0]]['inventory_hostname'] | default('') }}"
    messages_time_window: 50

  roles:
    - add_authorized_key
    - provision_docker
    - deploy_messagesproducer
