---
- name: Provision Cassandra
  hosts: localhost
  gather_facts: False
  vars_files:
      - "../config/default.yml"
  vars:
    # EC2 configuration
    instance_type: t2.small
    instance_name: Cassandra
    security_group: ['storestreams', 'default-ssh', 'default-cassandra']
    # host group name
    target_pub: target_cassandra_pub
    target_pub_ip: target_cassandra_pub_ip

  roles:
    - ec2

- name: Deploy Cassandra
  hosts: target_cassandra_pub
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
      - "../config/default.yml"

  roles:
    - provision_docker
    - add_authorized_key
    - deploy_cassandra
